---
- name: Manage Kubernetes Deployments
  hosts: localhost
  gather_facts: no
  vars:
    kubeconfig_path: /home/ubuntu/.kube/config
    kubectl_path: /home/ubuntu/bin/kubectl  # Added full path for kubectl

  tasks:
    - name: Set AWS credentials
      set_fact:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Verify AWS credentials
      debug:
        msg: "AWS Access Key ID: {{ AWS_ACCESS_KEY_ID }}"

    - name: Verify kubectl connection
      command: "{{ kubectl_path }} get nodes --kubeconfig={{ kubeconfig_path }}"
      register: kubectl_output
      failed_when: kubectl_output.rc != 0

    - debug:
        var: kubectl_output.stdout_lines

    - name: Delete old deployment
      command: "{{ kubectl_path }} delete -f /home/ubuntu/Deployment.yml --kubeconfig={{ kubeconfig_path }}"
      register: delete_deployment
      ignore_errors: yes

    - debug:
        var: delete_deployment

    - name: Delete old service
      command: "{{ kubectl_path }} delete -f /home/ubuntu/Service.yml --kubeconfig={{ kubeconfig_path }}"
      register: delete_service
      ignore_errors: yes

    - debug:
        var: delete_service

    - name: Create new deployment
      command: "{{ kubectl_path }} apply -f /home/ubuntu/Deployment.yml --kubeconfig={{ kubeconfig_path }} --validate=false"
      register: create_deployment
      failed_when: create_deployment.rc != 0

    - debug:
        var: create_deployment

    - name: Create new service
      command: "{{ kubectl_path }} apply -f /home/ubuntu/Service.yml --kubeconfig={{ kubeconfig_path }} --validate=false"
      register: create_service
      failed_when: create_service.rc != 0

    - debug:
        var: create_service
