- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config
      ignore_errors: true

    - name: Delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml --kubeconfig=/home/ubuntu/.kube/config
      ignore_errors: true

    - name: Create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config

    - name: Create new service
      command: kubectl apply -f /home/ubuntu/Service.yml --force --kubeconfig=/home/ubuntu/.kube/config

    - name: Make script executable
      command: chmod +x /home/ubuntu/kubect-port-forward.sh

    - name: Kubectl port forward nodeport to service port and run the command in background
      command: nohup /bin/sh "/home/ubuntu/kubect-port-forward.sh" --kubeconfig=/home/ubuntu/.kube/config
      async: 100000
      poll: 10
      register: scrout

    - name: Debug output
      debug:
        var: scrout.stdout_lines
