- hosts: all
  become: true
  become_user: root
  tasks:
    - name: delete old deployment
      command: /home/ubuntu/bin/kubectl delete -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config
      register: delete_deployment
      ignore_errors: true

    - name: Print delete deployment output
      debug:
        var: delete_deployment

    - name: delete old service
      command: /home/ubuntu/bin/kubectl delete -f /home/ubuntu/Service.yml --kubeconfig=/home/ubuntu/.kube/config
      register: delete_service
      ignore_errors: true

    - name: Print delete service output
      debug:
        var: delete_service

    - name: create new deployment
      command: /home/ubuntu/bin/kubectl apply -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config
      register: create_deployment

    - name: Print create deployment output
      debug:
        var: create_deployment

    - name: create new service
      command: /home/ubuntu/bin/kubectl apply -f /home/ubuntu/Service.yml --force --kubeconfig=/home/ubuntu/.kube/config
      register: create_service

    - name: Print create service output
      debug:
        var: create_service

    - name: make script executable
      command: chmod +x /home/ubuntu/kubect-port-forward.sh

    - name: kubectl port forward nodeport to service port and run the command in background
      command: nohup /bin/sh "/home/ubuntu/kubect-port-forward.sh" &
      async: 100000
      poll: 0
      register: port_forward_output

    - name: Print port forward output
      debug:
        var: port_forward_output
