---
- name: Kubernetes Deployment with AWS EKS
  hosts: all
  become: yes
  tasks:

    - name: Ensure AWS CLI is installed
      package:
        name: awscli
        state: present

    - name: Configure AWS credentials
      copy:
        dest: /home/ubuntu/.aws/credentials
        content: |
          [default]
          aws_access_key_id = AKIA34AMDK3ULDNQJBGY
          aws_secret_access_key = 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

    - name: Ensure AWS config file exists
      copy:
        dest: /home/ubuntu/.aws/config
        content: |
          [default]
          region = ap-south-1
      notify: set_permissions

    - name: Update kubeconfig
      command: aws eks update-kubeconfig --name CoffeeCluster --region ap-south-1
      register: kubeconfig_output
      ignore_errors: yes

    - name: Debug kubeconfig output
      debug:
        var: kubeconfig_output

  handlers:
    - name: set_permissions
      file:
        path: /home/ubuntu/.aws
        owner: ubuntu
        group: ubuntu
        mode: '0700'
